name: Workflow to test workflow commands
run-name: ${{ github.actor }} is testing out workflow commands
on:
  push:
    branches:
      - workflow-command/**
jobs:
  a-normal-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."

  job-with-messages:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::debug::A debug message"
      - run: echo "::notice::A notice message"
      - run: echo "::warning::A warningmessage"
      - run: echo "::error::An error message"

  a-fail-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from a step of a fail job"
      - run: exit 1
